### ISSUE TITLE
有相应论文吗？

### ISSUE THREAD

**Issue by zhouzhiwen2000** [RoxLRL/-#1]
请问这个工作有相应论文发表吗？比较好奇其具体细节，有助于我感兴趣的无人机信号分类的工作。
另外，指一个小小的问题，最后图中的FTT应该是FFT。

**Comment by RoxLRL** [comment]
您好，感谢您发现的问题。目前没有发表相关论文，如果做信号分类的话，建议使用深度学习，时频图像方面入手哦。



---原始邮件---
发件人: "Zhiwen ***@***.***&gt;
发送时间: 2024年9月5日(周四) 下午2:16
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [RoxLRL/DeModDJ_UAV_SIGNAL] 有相应论文吗？ (Issue #1)




 
请问这个工作有相应论文发表吗？比较好奇其具体细节，有助于我感兴趣的无人机信号分类的工作。
 另外，指一个小小的问题，最后图中的FTT应该是FFT。

**Comment by zhouzhiwen2000** [comment]
好的，谢谢你的建议。
